from .domain import ComplianceRequirement


ONBOARDING_REQUIREMENTS = [
    ComplianceRequirement(
        id="form-i9",
        label="Form I-9 employment eligibility verification",
        responsible_party="employee",
        applicability="Every employee hired to perform labor or services in the United States.",
        retention_rule="Retain for three years after hire or one year after employment ends, whichever is later.",
        data_classification="restricted",
        official_source="https://www.uscis.gov/i-9-central/retain-and-store-form-i-9",
    ),
    ComplianceRequirement(
        id="e-verify",
        label="E-Verify or E-Verify+ case",
        responsible_party="employer",
        applicability="Only when Benson is enrolled or a covered prime contract includes the FAR E-Verify clause; subcontract coverage depends on that clause and scope/value.",
        retention_rule="Follow the current E-Verify MOU and retain the case result with the related I-9 record.",
        data_classification="restricted",
        official_source="https://www.e-verify.gov/employers/federal-contractors",
    ),
    ComplianceRequirement(
        id="federal-w4",
        label="Federal Form W-4",
        responsible_party="employee",
        applicability="Every employee; not an independent-contractor form.",
        retention_rule="Keep the signed certificate in employer tax records while effective and for the required employment-tax record period.",
        data_classification="restricted",
        official_source="https://www.irs.gov/businesses/small-businesses-self-employed/hiring-employees",
    ),
    ComplianceRequirement(
        id="oregon-w4",
        label="Oregon Form OR-W-4",
        responsible_party="employee",
        applicability="Employees whose wages are subject to Oregon withholding.",
        retention_rule="Retain the effective withholding certificate with payroll tax records.",
        data_classification="restricted",
        official_source="https://www.oregon.gov/dor/programs/businesses/pages/withholding-and-payroll-tax.aspx",
    ),
    ComplianceRequirement(
        id="oregon-new-hire-report",
        label="Oregon new-hire report",
        responsible_party="employer",
        applicability="Employees reportable to the Oregon New Hire Reporting Program.",
        retention_rule="Retain submission confirmation under the approved payroll record schedule.",
        data_classification="restricted",
        official_source="https://sos.oregon.gov/business/Pages/employer-forms.aspx",
    ),
    ComplianceRequirement(
        id="payroll-enrollment",
        label="Payroll enrollment and payment election",
        responsible_party="employee",
        applicability="Employees. Direct deposit must remain optional where a lawful alternative is required.",
        retention_rule="Retain payroll authorization under the approved payroll record schedule.",
        data_classification="restricted",
        official_source="https://www.irs.gov/publications/p15",
    ),
    ComplianceRequirement(
        id="davis-bacon",
        label="Davis-Bacon classification and certified-payroll setup",
        responsible_party="employer",
        applicability="Workers on a contract or subcontract actually covered by DBRA clauses and its wage determination.",
        retention_rule="Retain covered contract, payroll, apprenticeship, and supporting records at least three years after prime-contract work completes.",
        data_classification="restricted",
        official_source="https://www.dol.gov/agencies/whd/forms/wh347",
    ),
    ComplianceRequirement(
        id="section-503-self-id",
        label="Section 503 voluntary disability self-identification invitation",
        responsible_party="employee",
        applicability="Only when current OFCCP federal-contract jurisdiction and invitation requirements apply.",
        retention_rule="Segregate confidential self-identification data and retain under the approved OFCCP schedule.",
        data_classification="restricted",
        official_source="https://www.dol.gov/agencies/ofccp/self-id-forms",
    ),
    ComplianceRequirement(
        id="vevraa-self-id",
        label="VEVRAA protected-veteran self-identification invitation",
        responsible_party="employee",
        applicability="Only when current OFCCP federal-contract jurisdiction and invitation requirements apply.",
        retention_rule="Segregate self-identification data and retain under the approved OFCCP schedule.",
        data_classification="restricted",
        official_source="https://www.dol.gov/agencies/ofccp/faqs/vevraa",
    ),
    ComplianceRequirement(
        id="contractor-w9",
        label="Form W-9",
        responsible_party="contractor",
        applicability="Only for a genuine independent contractor after worker classification is approved.",
        retention_rule="Retain with information-return and backup-withholding records.",
        data_classification="restricted",
        official_source="https://www.irs.gov/forms-pubs/about-form-w-9",
    ),
]
