"""user_mfa

Revision ID: 0232a8dbc760
Revises: a0b696ee2341
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0232a8dbc760"
down_revision: str | None = "a0b696ee2341"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("mfa_enabled", sa.Boolean(), server_default=sa.false(), nullable=False)
    )
    op.add_column("users", sa.Column("mfa_secret_encrypted", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("mfa_pending_secret_encrypted", sa.Text(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "mfa_recovery_code_hashes",
            sa.JSON(),
            server_default=sa.text("'[]'::json"),
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "mfa_pending_recovery_code_hashes",
            sa.JSON(),
            server_default=sa.text("'[]'::json"),
            nullable=False,
        ),
    )
    op.alter_column("users", "mfa_enabled", server_default=None)
    op.alter_column("users", "mfa_recovery_code_hashes", server_default=None)
    op.alter_column("users", "mfa_pending_recovery_code_hashes", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "mfa_pending_recovery_code_hashes")
    op.drop_column("users", "mfa_recovery_code_hashes")
    op.drop_column("users", "mfa_pending_secret_encrypted")
    op.drop_column("users", "mfa_secret_encrypted")
    op.drop_column("users", "mfa_enabled")
    # ### end Alembic commands ###
