DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'benson_app') THEN
        CREATE ROLE benson_app LOGIN PASSWORD 'benson-app-development-only' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
    END IF;
END
$$;

GRANT CONNECT ON DATABASE benson_erp TO benson_app;
GRANT USAGE ON SCHEMA public TO benson_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO benson_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO benson_app;
ALTER DEFAULT PRIVILEGES FOR ROLE benson IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO benson_app;
ALTER DEFAULT PRIVILEGES FOR ROLE benson IN SCHEMA public
    GRANT USAGE, SELECT ON SEQUENCES TO benson_app;
